### ISSUE TITLE
prior CICE releases

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE-svn-trunk#4]
If possible, it would be nice to add the CICE releases prior to those in the svn repository as branches here, just for safekeeping and historical interest.  (To me, they're sort of like looking at baby pictures.)  I have the following:
CICE.v1.0
CICE.v2.0
CICE.v2.0.1
CICE.v2.0.2
CICE.v3.0
CICE.v3.1
CICE.v3.14
The next one would have been v3.141, then v3.1415 ...  but we jumped to 4.0.
There's even a little documentation in there (not much).

What's the best way to go about this?

**Comment by apcraig** [comment]
I think the first question to ask is whether these releases are in the current CICE-svn-trunk repository?  What is the starting point of the current repo.  It is something like CICE4 with prior versions in CVS (or something else?)?  If we can identify certain versions in the current repo as matching up to the earliest releases, then we can probably tag them.  If we have to import the old releases from elsewhere somehow, then I'm not sure what is best to do.  On some level, the easiest thing is to just drop tar files onto the wiki page (or similar) so they are available.  If we actually want to try to construct a repo with history going back before CICE4, I doubt that is possible.  One final thought is that we could create branches in the current repo by just creating the branch and then overwriting it with the release tag of interest.  In that sense, the repo will look like we branched from CICE4 to create CICE1, but we probably don't care about history.  If we just want branches that contain the early releases, I think we can do that.  We just need to manually bring those onto each branch.  I can try to play around with this.  Where can I find the prior releases?

**Comment by eclare108213** [comment]
The CICE-svn-trunk repo does not include the releases prior to v4, because they were in the older cvs repository.  I don't think we need to construct a repo with the old history.  I was just hoping that we could include the old releases as branches similar to the newer ones, so they'd all show up in the same place.   I'll send the early releases to @apcraig.

**Comment by apcraig** [comment]
Added several new branches, presvn/tags/release-* for earlier releases.  Will close.  Please reopen or start another issue if there is anything else.

**Comment by eclare108213** [comment]
For clarification and future reference:  the new branches are only branches, not tags, because we do not want them showing up with the other releases -- they would be out of order, having been 'released' in github after the v4-v5 releases, and these very old versions of the code are not intended to be used.  The purpose of putting them here is for safekeeping and historical interest.  Their branches are structured similar to the v4-v5 releases (with 'tags' in the directory structure) to allow them to be simply tagged in the future, if/when that makes sense.
